from alembic import op # alembic is just a database migration tool, it generates SQL to work with whatever db we configure
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '5a0278e3ec9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic ###
    # TODO: adjust these to match what we actually have.
    op.create_table('games',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('grade_level', sa.String(length=50), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('game_url', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )


def downgrade():
    # TODO: adjust this too
    op.drop_table('games')
